Added typings
mercurius-js/auth pull request #6
Opened 2021-05-05 14:22 UTC by sharmapukar217

2021-05-05 15:12 UTC, jonnydgreen requested changes
Nice one! :) I've done an initial pass. Could you also add some types tests (using `tsd`) as well? You can use `mercurius-js` as a reference for this:
 - Example command: https://github.com/mercurius-js/mercurius/blob/master/package.json#L15
 - Example types test file: https://github.com/mercurius-js/mercurius/blob/master/test/types/index.ts

2021-05-05 15:13 UTC, mcollina requested changes
Could you add tests with https://www.npmjs.com/package/tsd?

2021-05-05 16:09 UTC, sharmapukar217 commented on index.d.ts
> +    args: Record<string, any>,
i thought { [argName: string]: any }  and Record<string, any> were similar

2021-05-05 16:12 UTC, jonnydgreen commented on index.d.ts
> +    args: Record<string, any>,
You are correct, yep - this is also fine as a default (the `{ [argName: string]: any }` came from what `graphql-js` has used)

2021-05-05 16:13 UTC, sharmapukar217 commented on index.d.ts
> +    args: Record<string, any>,
oh ok following `graphql-js`

2021-05-09 12:54 UTC, sharmapukar217 commented on index.d.ts
> +    context: MercuriusContext,
In order to accept generic, do we need to export a type for applyPolicy function ? I couldn't figure out other way to pass generic on function inside an object

2021-05-09 15:39 UTC, jonnydgreen commented on index.d.ts
> +    context: MercuriusContext,
Yep, exporting an `applyPolicyHandler` type should do the trick here, then you can pass the generics all the way through from the options type!

2021-05-10 13:44 UTC, closed without merging